### ISSUE TITLE
Game update issue

### ISSUE THREAD

**Issue by gogo42170** [XertroV/tm-editor-plus-plus#16]
Hi, since the last update of the game (yesterday), editor ++ tab doesn't appear anymore on openplanet

**Comment by XertroV** [comment]
it should work fine. have you restarted the game recently?
If E++ is up to date and a game restart doesn't fix it, something is odd. 

You have 0.8.99999993 right?

also, you can manually mark the version okay in settings. (Openplanet > Settings > Editor++ > Game Version Check)

**Comment by gogo42170** [comment]
It works again good :)
