### ISSUE TITLE
I lost pretty much my entire map becasue I used the offset blocks tool, how can I get it back

### ISSUE THREAD

**Issue by lemdak** [XertroV/tm-editor-plus-plus#17]
I lost pretty much my entire map because I used the offset blocks tool, how can I get it back. I tried offsetting it outside of the stadium and just cut my map off, it said to save and reload and the reloading meant I couldn't remove the change, I know have a quarter of my map left, how do I get it back.

**Comment by XertroV** [comment]
1. Always save a copy of your map when experimenting
2. Try pressing undo ('u' or ctrl+z or undo in editor toolbar)
3. Check autosave directory, copy any maps out so they don't get overridden
4. Failing that, if you have no backups, you're probably out of luck
