### ISSUE TITLE
"Please Load E++ Editor Plugin" when calculating shadows

### ISSUE THREAD

**Issue by ezio416** [XertroV/tm-editor-plus-plus#4]
The warning message appears nearly every time I calculate shadows, even though I do have the editor plugin enabled
<img width="1378" alt="Screenshot 2023-10-25 221037" src="https://github.com/XertroV/tm-editor-plus-plus/assets/37951898/5238779b-4e81-413a-9157-354af4e91824">

**Comment by XertroV** [comment]
Yep, it's because the editor plugin stops running while doing shadows. I need to figure out how to test for computing shadows before fixing -- it's a bit of a pain b/c obviously the UI is nearly unresponsive during this time.

**Comment by XertroV** [comment]
okay can fix this pretty easily. will be in next version
