### ISSUE TITLE
can't access some things in Inventory V2

### ISSUE THREAD

**Issue by ezio416** [XertroV/tm-editor-plus-plus#7]
I can click on everything except for custom items. Also when I click on macroblocks, the 2 subcategories are perpetually loading and won't let me access them

<img width="268" alt="Screenshot 2024-01-14 165908" src="https://github.com/XertroV/tm-editor-plus-plus/assets/37951898/672e2c19-e18d-446a-ac86-40f08b3b1cb5">

**Comment by XertroV** [comment]
fixed in e3f80e748b69436b718b5ec51efcc69227ba36f4
